# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 1.1.0
maven_group = com.madgique.map_without_stopping
archives_name = map_without_stopping
mod_id = map_without_stopping
enabled_platforms = fabric,forge

# Mod metadata
mod_display_name = Map Without Stopping
mod_description = Allows you to move while fullscreen maps (JourneyMap, Xaero) are open.
mod_authors = Madgique
mod_credits =
mod_license = LGPLv3
mod_sources = https://github.com/Madgique/map-without-stopping
mod_issue_tracker_url = https://github.com/Madgique/map-without-stopping/issues

# Minecraft properties
minecraft_version = 1.18.2
parchment_mc_version = 1.18.2
parchment_version = 2022.11.06

# Dependencies
architectury_api_version = 4.11.93
fabric_loader_version = 0.14.25
fabric_api_version = 0.77.0+1.18.2
forge_version = 40.2.21
mod_menu_version = 3.2.5
