modLoader = "javafml"
loaderVersion = "[4,)"
license = "LGPLv3"

[[mods]]
modId = "map_without_stopping"
version = "${version}"
displayName = "Map Without Stopping"
logoFile = "icon.png"
authors = "Madgique"
description = '''
Allows you to move while fullscreen maps (JourneyMap, Xaero) are open.
'''

[[dependencies.map_without_stopping]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.map_without_stopping]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "map_without_stopping.mixins.json"
